version: '3'
services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks:
      - container
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - container
networks:
  container:
    driver: bridge
